### PR TITLE
Make icons load properly, find them in more places, and fix a couple of bugs

### PR DESCRIPTION
**Pull request by stuartlangridge**

### CODE REVIEW

**Comment by rschroll** [comment]
I'm not getting icons to load with this.  I'm not sure why; I'm sure it 
was working for you.  I'll keep poking around, but if you can double 
check and make sure you didn't forget to commit a file, it'd be 
appreciated.

**Comment by stuartlangridge** [comment]
Icon finding should be better now. :)

**Comment by rschroll** [comment]
Yep.  I does seem to be working.  Two minor issues:

1) It looks like you can define multiple favicon links with different 
sizes.  I don't know how common this is, but presumably we can 
repurpose the code from the apple icons to check these as well.

2) I'm thinking that we should add /favicon.ico to the end of the list 
for sites that just use it.  We don't need to check that it exists 
here; the downloader code will have to missing files anyway.

**Comment by rschroll** [comment]
I did some history rewriting to remove an extraneous line.  Otherwise, this is all merged.  Hope this doesn't bother you too much.

**Pull request closed without merging**
